# Defines the structure and provenance of resource files.
TUDAT_RESOURCES_VERSION = "2.4"
TUDAT_RESOURCES_URL = "https://zenodo.org/records/21277280"
TUDAT_ZENODO_STATIC_RECORD = 21277280
TUDAT_ZENODO_ROLLING_RECORD = 21261530
TUDAT_ZENODO_STATIC_API_BASE = f"https://zenodo.org/api/records/{TUDAT_ZENODO_STATIC_RECORD}/files"
TUDAT_ZENODO_ROLLING_API_BASE = f"https://zenodo.org/api/records/{TUDAT_ZENODO_ROLLING_RECORD}/files"

TUDAT_ZENODO_STATIC_TARBALLS = {
    "spice_kernels/inpop19a_TCB_m100_p100_asc": "inpop19a_TCB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_asc": "inpop19a_TDB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_spice": "inpop19a_TDB_m100_p100_spice.tar.gz",
    "star_catalog_biases": "star_catalog_biases.tar.gz",
    "atmosphere_tables": "atmosphere_tables.tar.gz",
    "earth_deformation": "earth_deformation.tar.gz",
    "ephemeris": "ephemeris.tar.gz",
    "gravity_models": "gravity_models.tar.gz",
    "quadrature": "quadrature.tar.gz",
    "spice_kernels": "spice_kernels.tar.gz",
    "station_locations": "station_locations.tar.gz",
}

TUDAT_ZENODO_ROLLING_PREFIXES = {
    "earth_orientation",
    "space_weather",
}


def _rewrite_zenodo_tarball_url(path: str, url: str) -> str:
    if not url.startswith(TUDAT_RESOURCES_URL):
        return url

    for prefix, tarball in sorted(
        TUDAT_ZENODO_STATIC_TARBALLS.items(), key=lambda item: -len(item[0])
    ):
        if path == prefix or path.startswith(prefix + "/"):
            return f"{TUDAT_ZENODO_STATIC_API_BASE}/{tarball}/content"

    for prefix in TUDAT_ZENODO_ROLLING_PREFIXES:
        if path == prefix or path.startswith(prefix + "/"):
            return f"{TUDAT_ZENODO_ROLLING_API_BASE}/resource-rolling.tar.gz/content"

    return url

_RAW_DATA_REGISTRY = {
    "atmosphere_tables/dtm_mars.dat": f"{TUDAT_RESOURCES_URL}/atmosphere_tables/dtm_mars.dat",
    "atmosphere_tables/MCDMeanAtmosphere.dat": f"{TUDAT_RESOURCES_URL}/atmosphere_tables/MCDMeanAtmosphere.dat",
    "atmosphere_tables/nrlmsise00_validation_data.pkl": f"{TUDAT_RESOURCES_URL}/atmosphere_tables/nrlmsise00_validation_data.pkl",
    "atmosphere_tables/USSA1976Until100kmPer100mUntil1000kmPer1000m_wHR_GC.dat": f"{TUDAT_RESOURCES_URL}/atmosphere_tables/USSA1976Until100kmPer100mUntil1000kmPer1000m_wHR_GC.dat",
    "atmosphere_tables/USSA1976Until100kmPer100mUntil1000kmPer1000m.dat": f"{TUDAT_RESOURCES_URL}/atmosphere_tables/USSA1976Until100kmPer100mUntil1000kmPer1000m.dat",
    "atmosphere_tables/USSA1976Until86kmPer100m.dat": f"{TUDAT_RESOURCES_URL}/atmosphere_tables/USSA1976Until86kmPer100m.dat",
    "atmosphere_tables/MCDMeanAtmosphereTimeAverage/density.dat": f"{TUDAT_RESOURCES_URL}/atmosphere_tables/MCDMeanAtmosphereTimeAverage/density.dat",
    "atmosphere_tables/MCDMeanAtmosphereTimeAverage/gasConstant.dat": f"{TUDAT_RESOURCES_URL}/atmosphere_tables/MCDMeanAtmosphereTimeAverage/gasConstant.dat",
    "atmosphere_tables/MCDMeanAtmosphereTimeAverage/pressure.dat": f"{TUDAT_RESOURCES_URL}/atmosphere_tables/MCDMeanAtmosphereTimeAverage/pressure.dat",
    "atmosphere_tables/MCDMeanAtmosphereTimeAverage/specificHeatRatio.dat": f"{TUDAT_RESOURCES_URL}/atmosphere_tables/MCDMeanAtmosphereTimeAverage/specificHeatRatio.dat",
    "atmosphere_tables/MCDMeanAtmosphereTimeAverage/temperature.dat": f"{TUDAT_RESOURCES_URL}/atmosphere_tables/MCDMeanAtmosphereTimeAverage/temperature.dat",
    "atmosphere_tables/vmf3/anm_bh.txt": f"{TUDAT_RESOURCES_URL}/atmosphere_tables/vmf3/anm_bh.txt",
    "atmosphere_tables/vmf3/anm_bw.txt": f"{TUDAT_RESOURCES_URL}/atmosphere_tables/vmf3/anm_bw.txt",
    "atmosphere_tables/vmf3/anm_ch.txt": f"{TUDAT_RESOURCES_URL}/atmosphere_tables/vmf3/anm_ch.txt",
    "atmosphere_tables/vmf3/anm_cw.txt": f"{TUDAT_RESOURCES_URL}/atmosphere_tables/vmf3/anm_cw.txt",
    "atmosphere_tables/vmf3/bnm_bh.txt": f"{TUDAT_RESOURCES_URL}/atmosphere_tables/vmf3/bnm_bh.txt",
    "atmosphere_tables/vmf3/bnm_bw.txt": f"{TUDAT_RESOURCES_URL}/atmosphere_tables/vmf3/bnm_bw.txt",
    "atmosphere_tables/vmf3/bnm_ch.txt": f"{TUDAT_RESOURCES_URL}/atmosphere_tables/vmf3/bnm_ch.txt",
    "atmosphere_tables/vmf3/bnm_cw.txt": f"{TUDAT_RESOURCES_URL}/atmosphere_tables/vmf3/bnm_cw.txt",
    "earth_deformation/diurnalDisplacementFrequencyDependence.txt": f"{TUDAT_RESOURCES_URL}/earth_deformation/diurnalDisplacementFrequencyDependence.txt",
    "earth_deformation/diurnalDisplacementFrequencyDependence2.txt": f"{TUDAT_RESOURCES_URL}/earth_deformation/diurnalDisplacementFrequencyDependence2.txt",
    "earth_deformation/ilrsStations.blq": f"{TUDAT_RESOURCES_URL}/earth_deformation/ilrsStations.blq",
    "earth_deformation/longPeriodDisplacementFrequencyDependence.txt": f"{TUDAT_RESOURCES_URL}/earth_deformation/longPeriodDisplacementFrequencyDependence.txt",
    "earth_deformation/oceanTidetest.blq": f"{TUDAT_RESOURCES_URL}/earth_deformation/oceanTidetest.blq",
    "earth_orientation/eopc04_08_IAU2000.62-now.txt": f"{TUDAT_RESOURCES_URL}/earth_orientation/eopc04_08_IAU2000.62-now.txt",
    "earth_orientation/eopc04_14_IAU2000.62-now.txt": "https://datacenter.iers.org/data/224/eopc04_14_IAU2000.62-now.txt",
    "earth_orientation/historicalDeltaT.txt": f"{TUDAT_RESOURCES_URL}/earth_orientation/historicalDeltaT.txt",
    "earth_orientation/polarMotionLibrationAmplitudes.txt": f"{TUDAT_RESOURCES_URL}/earth_orientation/polarMotionLibrationAmplitudes.txt",
    "earth_orientation/polarMotionLibrationAmplitudesQuasiDiurnalOnly.txt": f"{TUDAT_RESOURCES_URL}/earth_orientation/polarMotionLibrationAmplitudesQuasiDiurnalOnly.txt",
    "earth_orientation/polarMotionLibrationFundamentalArgumentMultipliers.txt": f"{TUDAT_RESOURCES_URL}/earth_orientation/polarMotionLibrationFundamentalArgumentMultipliers.txt",
    "earth_orientation/polarMotionLibrationFundamentalArgumentMultipliersQuasiDiurnalOnly.txt": f"{TUDAT_RESOURCES_URL}/earth_orientation/polarMotionLibrationFundamentalArgumentMultipliersQuasiDiurnalOnly.txt",
    "earth_orientation/polarMotionOceanTidesAmplitudes.txt": f"{TUDAT_RESOURCES_URL}/earth_orientation/polarMotionOceanTidesAmplitudes.txt",
    "earth_orientation/polarMotionOceanTidesFundamentalArgumentMultipliers.txt": f"{TUDAT_RESOURCES_URL}/earth_orientation/polarMotionOceanTidesFundamentalArgumentMultipliers.txt",
    "earth_orientation/utcLibrationAmplitudes.txt": f"{TUDAT_RESOURCES_URL}/earth_orientation/utcLibrationAmplitudes.txt",
    "earth_orientation/utcLibrationFundamentalArgumentMultipliers.txt": f"{TUDAT_RESOURCES_URL}/earth_orientation/utcLibrationFundamentalArgumentMultipliers.txt",
    "earth_orientation/utcOceanTidesAmplitudes.txt": f"{TUDAT_RESOURCES_URL}/earth_orientation/utcOceanTidesAmplitudes.txt",
    "earth_orientation/utcOceanTidesFundamentalArgumentMultipliers.txt": f"{TUDAT_RESOURCES_URL}/earth_orientation/utcOceanTidesFundamentalArgumentMultipliers.txt",
    "ephemeris/eros_obs.txt": f"{TUDAT_RESOURCES_URL}/ephemeris/eros_obs.txt",
    "ephemeris/p_elem_t1.txt": f"{TUDAT_RESOURCES_URL}/ephemeris/p_elem_t1.txt",
    "ephemeris/p_elem_t2.txt": f"{TUDAT_RESOURCES_URL}/ephemeris/p_elem_t2.txt",
    "gravity_models/Earth/egm96.txt": f"{TUDAT_RESOURCES_URL}/gravity_models/Earth/egm96.txt",
    "gravity_models/Earth/ggm02c.txt": f"{TUDAT_RESOURCES_URL}/gravity_models/Earth/ggm02c.txt",
    "gravity_models/Earth/ggm02s.txt": f"{TUDAT_RESOURCES_URL}/gravity_models/Earth/ggm02s.txt",
    "gravity_models/Earth/GOCO05c.txt": f"{TUDAT_RESOURCES_URL}/gravity_models/Earth/GOCO05c.txt",
    "gravity_models/Mars/jgmro120d.txt": f"{TUDAT_RESOURCES_URL}/gravity_models/Mars/jgmro120d.txt",
    "gravity_models/Mercury/jgmess_160a_sha.tab": "https://pds-geosciences.wustl.edu/messenger/mess-h-rss_mla-5-sdp-v1/messrs_1001/data/shadr/jgmess_160a_sha.tab",
    "gravity_models/Moon/gggrx_1200l_sha.tab": "https://pds-geosciences.wustl.edu/grail/grail-l-lgrs-5-rdr-v1/grail_1001/shadr/gggrx_1200l_sha.tab",
    "gravity_models/Moon/glgm3150.txt": f"{TUDAT_RESOURCES_URL}/gravity_models/Moon/glgm3150.txt",
    "gravity_models/Moon/lpe200.txt": f"{TUDAT_RESOURCES_URL}/gravity_models/Moon/lpe200.txt",
    "gravity_models/Venus/shgj180u.a01": "https://pds-geosciences.wustl.edu/mgn/mgn-v-rss-5-gravity-l2-v1/mg_5201/gravity/shgj180u.a01",
    "quadrature/gaussianNodes.txt": f"{TUDAT_RESOURCES_URL}/quadrature/gaussianNodes.txt",
    "quadrature/gaussianWeights.txt": f"{TUDAT_RESOURCES_URL}/quadrature/gaussianWeights.txt",
    "space_weather/sw19571001.txt": "https://celestrak.org/SpaceData/sw19571001.txt",
    "spice_kernels/celestrak.json": f"{TUDAT_RESOURCES_URL}/spice_kernels/celestrak.json",
    "spice_kernels/codes_300ast_20100725.bsp": "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/asteroids/codes_300ast_20100725.bsp",
    "spice_kernels/codes_300ast_20100725.cmt": "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/asteroids/codes_300ast_20100725.cmt",
    "spice_kernels/codes_300ast_20100725.tf": "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/asteroids/codes_300ast_20100725.tf",
    "spice_kernels/de430_mar097_small.bsp": f"{TUDAT_RESOURCES_URL}/spice_kernels/de430_mar097_small.bsp",
    "spice_kernels/de440.bsp": "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/de440.bsp",
    "spice_kernels/earth_200101_990825_predict.bpc": "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/a_old_versions/earth_200101_990825_predict.bpc",
    "spice_kernels/earth_200101_990825_predict.cmt": "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/a_old_versions/earth_200101_990825_predict.cmt",
    "spice_kernels/earth_720101_230601.bpc": "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/a_old_versions/earth_720101_230601.bpc",
    "spice_kernels/earth_720101_230601.cmt": "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/a_old_versions/earth_720101_230601.cmt",
    "spice_kernels/earth_fixed.tf": "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/earth_fixed.tf",
    "spice_kernels/earth_latest_high_prec.bpc": "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/earth_latest_high_prec.bpc",
    "spice_kernels/earth_latest_high_prec.cmt": "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/earth_latest_high_prec.cmt",
    "spice_kernels/gm_de431.tpc": "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/gm_de431.tpc",
    "spice_kernels/inpop19a_TCB_m100_p100_asc/inpop19a_TCB_m100_p100_asc_header.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TCB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TCB_m100_p100_asc/inpop19a_TCB_m100_p100_asc_pos_Ear.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TCB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TCB_m100_p100_asc/inpop19a_TCB_m100_p100_asc_pos_EMB.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TCB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TCB_m100_p100_asc/inpop19a_TCB_m100_p100_asc_pos_Jup.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TCB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TCB_m100_p100_asc/inpop19a_TCB_m100_p100_asc_pos_Lib.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TCB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TCB_m100_p100_asc/inpop19a_TCB_m100_p100_asc_pos_Mar.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TCB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TCB_m100_p100_asc/inpop19a_TCB_m100_p100_asc_pos_Mer.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TCB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TCB_m100_p100_asc/inpop19a_TCB_m100_p100_asc_pos_Moo.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TCB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TCB_m100_p100_asc/inpop19a_TCB_m100_p100_asc_pos_Nep.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TCB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TCB_m100_p100_asc/inpop19a_TCB_m100_p100_asc_pos_Plu.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TCB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TCB_m100_p100_asc/inpop19a_TCB_m100_p100_asc_pos_Sat.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TCB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TCB_m100_p100_asc/inpop19a_TCB_m100_p100_asc_pos_Sun.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TCB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TCB_m100_p100_asc/inpop19a_TCB_m100_p100_asc_pos_TCG.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TCB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TCB_m100_p100_asc/inpop19a_TCB_m100_p100_asc_pos_Ura.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TCB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TCB_m100_p100_asc/inpop19a_TCB_m100_p100_asc_pos_Ven.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TCB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TCB_m100_p100_asc/inpop19a_TCB_m100_p100_asc_vel_Ear.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TCB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TCB_m100_p100_asc/inpop19a_TCB_m100_p100_asc_vel_EMB.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TCB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TCB_m100_p100_asc/inpop19a_TCB_m100_p100_asc_vel_Jup.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TCB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TCB_m100_p100_asc/inpop19a_TCB_m100_p100_asc_vel_Lib.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TCB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TCB_m100_p100_asc/inpop19a_TCB_m100_p100_asc_vel_Mar.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TCB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TCB_m100_p100_asc/inpop19a_TCB_m100_p100_asc_vel_Mer.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TCB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TCB_m100_p100_asc/inpop19a_TCB_m100_p100_asc_vel_Moo.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TCB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TCB_m100_p100_asc/inpop19a_TCB_m100_p100_asc_vel_Nep.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TCB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TCB_m100_p100_asc/inpop19a_TCB_m100_p100_asc_vel_Plu.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TCB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TCB_m100_p100_asc/inpop19a_TCB_m100_p100_asc_vel_Sat.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TCB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TCB_m100_p100_asc/inpop19a_TCB_m100_p100_asc_vel_Sun.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TCB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TCB_m100_p100_asc/inpop19a_TCB_m100_p100_asc_vel_Ura.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TCB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TCB_m100_p100_asc/inpop19a_TCB_m100_p100_asc_vel_Ven.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TCB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_asc/inpop19a_TDB_m100_p100_asc_header.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_asc/inpop19a_TDB_m100_p100_asc_pos_Ear.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_asc/inpop19a_TDB_m100_p100_asc_pos_EMB.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_asc/inpop19a_TDB_m100_p100_asc_pos_Jup.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_asc/inpop19a_TDB_m100_p100_asc_pos_Lib.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_asc/inpop19a_TDB_m100_p100_asc_pos_Mar.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_asc/inpop19a_TDB_m100_p100_asc_pos_Mer.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_asc/inpop19a_TDB_m100_p100_asc_pos_Moo.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_asc/inpop19a_TDB_m100_p100_asc_pos_Nep.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_asc/inpop19a_TDB_m100_p100_asc_pos_Plu.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_asc/inpop19a_TDB_m100_p100_asc_pos_Sat.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_asc/inpop19a_TDB_m100_p100_asc_pos_Sun.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_asc/inpop19a_TDB_m100_p100_asc_pos_TT.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_asc/inpop19a_TDB_m100_p100_asc_pos_Ura.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_asc/inpop19a_TDB_m100_p100_asc_pos_Ven.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_asc/inpop19a_TDB_m100_p100_asc_vel_Ear.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_asc/inpop19a_TDB_m100_p100_asc_vel_EMB.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_asc/inpop19a_TDB_m100_p100_asc_vel_Jup.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_asc/inpop19a_TDB_m100_p100_asc_vel_Lib.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_asc/inpop19a_TDB_m100_p100_asc_vel_Mar.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_asc/inpop19a_TDB_m100_p100_asc_vel_Mer.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_asc/inpop19a_TDB_m100_p100_asc_vel_Moo.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_asc/inpop19a_TDB_m100_p100_asc_vel_Nep.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_asc/inpop19a_TDB_m100_p100_asc_vel_Plu.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_asc/inpop19a_TDB_m100_p100_asc_vel_Sat.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_asc/inpop19a_TDB_m100_p100_asc_vel_Sun.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_asc/inpop19a_TDB_m100_p100_asc_vel_Ura.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_asc/inpop19a_TDB_m100_p100_asc_vel_Ven.asc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_asc.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_spice/inpop19a_TDB_m100_p100_spice.bpc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_spice.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_spice/inpop19a_TDB_m100_p100_spice.bsp": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_spice.tar.gz",
    "spice_kernels/inpop19a_TDB_m100_p100_spice/inpop19a_TDB_m100_p100_spice.tpc": "https://ftp.imcce.fr/pub/ephem/planets/inpop19a/inpop19a_TDB_m100_p100_spice.tar.gz",
    "spice_kernels/juice_mat_crema_4_0_20220601_20330626_v01.bsp": "https://spiftp.esac.esa.int/data/SPICE/JUICE/kernels/spk/juice_mat_crema_4_0_20220601_20330626_v01.bsp",
    "spice_kernels/mars_iau2000_v1.tpc": "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/mars_iau2000_v1.tpc",
    "spice_kernels/moon_080317.tf": "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/fk/satellites/moon_080317.tf",
    "spice_kernels/moon_assoc_pa.tf": "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/fk/satellites/moon_assoc_pa.tf",
    "spice_kernels/moon_de440_200625.tf": "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/fk/satellites/a_old_versions/moon_de440_200625.tf",
    "spice_kernels/moon_pa_de440_200625.bpc": "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/moon_pa_de440_200625.bpc",
    "spice_kernels/moon_pa_de440_200625.cmt": "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/moon_pa_de440_200625.cmt",
    "spice_kernels/naif.json": f"{TUDAT_RESOURCES_URL}/spice_kernels/naif.json",
    "spice_kernels/naif0012.tls": "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/lsk/naif0012.tls",
    "spice_kernels/NOE-4-2020.bsp": "https://ftp.imcce.fr/pub/ephem/satel/NOE/MARS/2020/NOE-4-2020.bsp",
    "spice_kernels/NOE-4-2020.tpc": "https://ftp.imcce.fr/pub/ephem/satel/NOE/MARS/2020/NOE-4-2020.tpc",
    "spice_kernels/NOE-5-2021.bsp": "https://ftp.imcce.fr/pub/ephem/satel/NOE/JUPITER/2021/NOE-5-2021.bsp",
    "spice_kernels/NOE-5-2021.tpc": "https://ftp.imcce.fr/pub/ephem/satel/NOE/JUPITER/2021/NOE-5-2021.tpc",
    "spice_kernels/NOE-6-2018-MAIN-v2.bsp": "https://ftp.imcce.fr/pub/ephem/satel/NOE/SATURNE/2018/NOE-6-2018-MAIN-v2.bsp",
    "spice_kernels/NOE-6-2018-MAIN-v2.tpc": "https://ftp.imcce.fr/pub/ephem/satel/NOE/SATURNE/2018/NOE-6-2018-MAIN-v2.tpc",
    "spice_kernels/pck00010.tpc": "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/pck00010.tpc",
    "spice_kernels/pck00011.tpc": "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/pck00011.tpc",
    "spice_kernels/tudat_merged_spk_kernel.bsp": f"{TUDAT_RESOURCES_URL}/spice_kernels/tudat_merged_spk_kernel.bsp",
    "spice_kernels/tudat_merged_spk_kernel.inp": f"{TUDAT_RESOURCES_URL}/spice_kernels/tudat_merged_spk_kernel.inp",
    "spice_kernels/tudat_space.json": f"{TUDAT_RESOURCES_URL}/spice_kernels/tudat_space.json",
    "star_catalog_biases/debias_2018/bias.dat": f"{TUDAT_RESOURCES_URL}/star_catalog_biases/debias_2018/bias.dat",
    "star_catalog_biases/debias_2018/README.txt": f"{TUDAT_RESOURCES_URL}/star_catalog_biases/debias_2018/README.txt",
    "star_catalog_biases/debias_2018/tiles.dat": f"{TUDAT_RESOURCES_URL}/star_catalog_biases/debias_2018/tiles.dat",
    "station_locations/glo.sit": f"{TUDAT_RESOURCES_URL}/station_locations/glo.sit",
    "station_locations/glo.vel": f"{TUDAT_RESOURCES_URL}/station_locations/glo.vel",
    "station_locations/mpc_codes.dat": f"{TUDAT_RESOURCES_URL}/station_locations/mpc_codes.dat",
    "station_locations/mpc.sit": f"{TUDAT_RESOURCES_URL}/station_locations/mpc.sit",
    "station_locations/mpc.vel": f"{TUDAT_RESOURCES_URL}/station_locations/mpc.vel",
    "station_locations/ns_codes.dat": f"{TUDAT_RESOURCES_URL}/station_locations/ns_codes.dat",
}

DATA_REGISTRY = {
    key: _rewrite_zenodo_tarball_url(key, url)
    for key, url in _RAW_DATA_REGISTRY.items()
}
