# ====================================================================
#             WARNING: DO NOT MANUALLY CHANGE THIS FILE!
# ====================================================================
# 
# This file is automatically generated before every `tudatpy` release.
# The purpose of this file is manually import all members of 
# 
#     tudatpy.numerical_simulation.environment_setup.vehicle_systems
# 
# to make autocompletion suggestions of C++ tudatpy modules possible.

# ----------------------------------------
#                 METHODS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.environment_setup.vehicle_systems import \
     body_panel_settings, \
     body_tracking_panel_geometry, \
     box_wing_panelled_body_settings, \
     frame_fixed_panel_geometry, \
     full_panelled_body_settings, \
     time_varying_panel_geometry
# ----------------------------------------
#                 OBJECTS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.environment_setup.vehicle_systems import \
     BodyPanelGeometrySettings, \
     BodyPanelSettings, \
     FullPanelledBodySettings