# ====================================================================
#             WARNING: DO NOT MANUALLY CHANGE THIS FILE!
# ====================================================================
# 
# This file is automatically generated before every `tudatpy` release.
# The purpose of this file is manually import all members of 
# 
#     tudatpy.numerical_simulation.environment_setup.atmosphere
# 
# to make autocompletion suggestions of C++ tudatpy modules possible.

# ----------------------------------------
#                 METHODS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.environment_setup.atmosphere import \
     constant_wind_model, \
     custom_constant_temperature, \
     custom_four_dimensional_constant_temperature, \
     custom_wind_model, \
     exponential, \
     exponential_predefined, \
     nrlmsise00, \
     scaled_by_constant, \
     scaled_by_function, \
     tabulated, \
     us76
# ----------------------------------------
#                 OBJECTS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.environment_setup.atmosphere import \
     AtmosphereDependentVariables, \
     AtmosphereSettings, \
     ExponentialAtmosphereSettings, \
     WindModelSettings, \
     tabulated_density, \
     tabulated_gas_constant, \
     tabulated_molar_mass, \
     tabulated_pressure, \
     tabulated_specific_heat_ratio, \
     tabulated_temperature