# ====================================================================
#             WARNING: DO NOT MANUALLY CHANGE THIS FILE!
# ====================================================================
# 
# This file is automatically generated before every `tudatpy` release.
# The purpose of this file is manually import all members of 
# 
#     tudatpy.numerical_simulation.environment_setup.rotation_model
# 
# to make autocompletion suggestions of C++ tudatpy modules possible.

# ----------------------------------------
#                 METHODS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.environment_setup.rotation_model import \
     aerodynamic_angle_based, \
     constant_rotation_model, \
     custom_inertial_direction_based, \
     custom_rotation_model, \
     gcrs_to_itrs, \
     mars_high_accuracy, \
     orbital_state_direction_based, \
     simple, \
     simple_from_spice, \
     spice, \
     synchronous, \
     zero_pitch_moment_aerodynamic_angle_based
# ----------------------------------------
#                 OBJECTS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.environment_setup.rotation_model import \
     IAUConventions, \
     PlanetaryRotationModelSettings, \
     RotationModelSettings, \
     RotationModelType, \
     SimpleRotationModelSettings, \
     gcrs_to_itrs_rotation_model, \
     iau_2000_a, \
     iau_2000_b, \
     iau_2006, \
     planetary_rotation_model, \
     simple_rotational_model, \
     spice_rotation_model, \
     synchronous_rotation_model