# ====================================================================
#             WARNING: DO NOT MANUALLY CHANGE THIS FILE!
# ====================================================================
# 
# This file is automatically generated before every `tudatpy` release.
# The purpose of this file is manually import all members of 
# 
#     tudatpy.astro.element_conversion
# 
# to make autocompletion suggestions of C++ tudatpy modules possible.

# ----------------------------------------
#                 METHODS                 
# ----------------------------------------
from tudatpy.kernel.astro.element_conversion import \
     cartesian_to_keplerian, \
     cartesian_to_mee, \
     cartesian_to_mee_manual_singularity, \
     cartesian_to_spherical, \
     convert_position_elements, \
     delta_mean_anomaly_to_elapsed_time, \
     eccentric_to_mean_anomaly, \
     eccentric_to_true_anomaly, \
     eclipj2000_state_to_teme, \
     elapsed_time_to_delta_mean_anomaly, \
     flip_mee_singularity, \
     j2000_state_to_teme, \
     keplerian_to_cartesian, \
     keplerian_to_cartesian_elementwise, \
     keplerian_to_mee, \
     keplerian_to_mee_manual_singularity, \
     mean_motion_to_semi_major_axis, \
     mean_to_eccentric_anomaly, \
     mean_to_true_anomaly, \
     mee_to_cartesian, \
     mee_to_keplerian, \
     quaternion_entries_to_rotation_matrix, \
     rotation_matrix_to_quaternion_entries, \
     semi_major_axis_to_mean_motion, \
     spherical_to_cartesian, \
     spherical_to_cartesian_elementwise, \
     teme_state_to_eclipj2000, \
     teme_state_to_j2000, \
     true_to_eccentric_anomaly, \
     true_to_mean_anomaly
# ----------------------------------------
#                 OBJECTS                 
# ----------------------------------------
from tudatpy.kernel.astro.element_conversion import \
     KeplerianElementIndices, \
     PositionElementTypes, \
     SphericalOrbitalStateElementIndices, \
     argument_of_periapsis_index, \
     cartesian_position_type, \
     eccentricity_index, \
     flight_path_index, \
     geodetic_position_type, \
     heading_angle_index, \
     inclination_index, \
     latitude_index, \
     longitude_index, \
     longitude_of_ascending_node_index, \
     radius_index, \
     semi_latus_rectum_index, \
     semi_major_axis_index, \
     speed_index, \
     spherical_position_type, \
     true_anomaly_index