from tudatpy._deprecation import property_deprecation_decorator
from tudatpy.kernel.estimation.observations import *

SingleObservationSet.ancilliary_settings = property_deprecation_decorator("SingleObservationSet.ancilliary_settings", "SingleObservationSet.ancillary_settings")(SingleObservationSet.ancillary_settings)
