# ====================================================================
#             WARNING: DO NOT MANUALLY CHANGE THIS FILE!
# ====================================================================
# 
# This file is automatically generated before every `tudatpy` release.
# The purpose of this file is manually import all members of 
# 
#     tudatpy.astro.fundamentals
# 
# to make autocompletion suggestions of C++ tudatpy modules possible.

# ----------------------------------------
#                 METHODS                 
# ----------------------------------------
from tudatpy.kernel.astro.fundamentals import \
     compute_shadow_function