# ====================================================================
#             WARNING: DO NOT MANUALLY CHANGE THIS FILE!
# ====================================================================
# 
# This file is automatically generated before every `tudatpy` release.
# The purpose of this file is manually import all members of 
# 
#     tudatpy.numerical_simulation.propagation_setup.mass_rate
# 
# to make autocompletion suggestions of C++ tudatpy modules possible.

# ----------------------------------------
#                 METHODS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.propagation_setup.mass_rate import \
     custom, \
     custom_mass_rate, \
     from_thrust
# ----------------------------------------
#                 OBJECTS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.propagation_setup.mass_rate import \
     AvailableMassRateModels, \
     CustomMassRateSettings, \
     FromThrustMassRateSettings, \
     MassRateModelSettings, \
     custom_mass_rate_type, \
     from_thrust_mass_rate_type, \
     undefined_mass_rate_type