# ====================================================================
#             WARNING: DO NOT MANUALLY CHANGE THIS FILE!
# ====================================================================
# 
# This file is automatically generated before every `tudatpy` release.
# The purpose of this file is manually import all members of 
# 
#     tudatpy.math.geometry
# 
# to make autocompletion suggestions of C++ tudatpy modules possible.

# ----------------------------------------
#                 OBJECTS                 
# ----------------------------------------
from tudatpy.kernel.math.geometry import \
     Capsule, \
     CompositeSurfaceGeometry, \
     SurfaceGeometry