# ====================================================================
#             WARNING: DO NOT MANUALLY CHANGE THIS FILE!
# ====================================================================
# 
# This file is automatically generated before every `tudatpy` release.
# The purpose of this file is manually import all members of 
# 
#     tudatpy.math.root_finders
# 
# to make autocompletion suggestions of C++ tudatpy modules possible.

# ----------------------------------------
#                 METHODS                 
# ----------------------------------------
from tudatpy.kernel.math.statistics import \
     calculate_allan_variance_of_dataset, \
     convert_allan_variance_amplitudes_to_phase_noise_amplitudes
     
# ----------------------------------------
#                 OBJECTS                 
# ----------------------------------------
