name: Report a bug
description: Something is not working as expected
title: "[BUG]: <Short and descriptive title>"
labels: "type: bug"

body:
- type: markdown
  attributes:
    value: >
      Thank you for taking the time to file a bug report!

- type: textarea
  attributes:
    label: "Describe the issue:"
    placeholder: |
      A clear and concise description of what the bug is.
  validations:
    required: true

- type: textarea
  attributes:
    label: "How to reproduce the issue:"
    description: >
      Help us reproduce the issue by listing steps, and including code snippets, error messages, screenshots, or links to the relevant files in our Github repository.
  validations:
    required: true

- type: textarea
  attributes:
    label: "OS and Python version:"
    placeholder: |
      OS: << macOS Intel/ARM, Linux, Windows >>
      Python: << e.g. 3.12 >>
  validations:
    required: true

- type: textarea
  attributes:
    label: "Expected behavior:"
    placeholder: |
      Describe what you expected to happen.
  validations:
    required: false

- type: textarea
  attributes:
    label: "Current behavior:"
    placeholder: |
      Describe what happened instead.
  validations:
    required: false

- type: textarea
  attributes:
    label: "Additional context:"
    description: |
      Include any other relevant context, or attach screenshots.
    placeholder: |
      << your explanation here >>
  validations:
    required: false
