# ====================================================================
#             WARNING: DO NOT MANUALLY CHANGE THIS FILE!
# ====================================================================
# 
# This file is automatically generated before every `tudatpy` release.
# The purpose of this file is manually import all members of 
# 
#     tudatpy.numerical_simulation.environment_setup.gravity_field_variation
# 
# to make autocompletion suggestions of C++ tudatpy modules possible.

# ----------------------------------------
#                 METHODS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.environment_setup.gravity_field_variation import \
     mode_coupled_solid_body_tide, \
     periodic, \
     polynomial, \
     single_period_periodic, \
     single_power_polynomial, \
     solid_body_tide, \
     solid_body_tide_complex_k, \
     solid_body_tide_degree_order_variable_complex_k, \
     solid_body_tide_degree_order_variable_k, \
     solid_body_tide_degree_variable_complex_k, \
     solid_body_tide_degree_variable_k, \
     solid_multi_body_tide_degree_order_variable_k, \
     tabulated
# ----------------------------------------
#                 OBJECTS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.environment_setup.gravity_field_variation import \
     BasicSolidBodyGravityFieldVariationSettings, \
     BodyDeformationTypes, \
     GravityFieldVariationSettings, \
     basic_solid_body, \
     tabulated_deformation