# ====================================================================
#             WARNING: DO NOT MANUALLY CHANGE THIS FILE!
# ====================================================================
# 
# This file is automatically generated before every `tudatpy` release.
# The purpose of this file is manually import all members of 
# 
#     tudatpy.numerical_simulation.propagation_setup.torque
# 
# to make autocompletion suggestions of C++ tudatpy modules possible.

# ----------------------------------------
#                 METHODS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.propagation_setup.torque import \
     aerodynamic, \
     custom, \
     custom_torque, \
     second_degree_gravitational, \
     spherical_harmonic_gravitational
# ----------------------------------------
#                 OBJECTS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.propagation_setup.torque import \
     AvailableTorque, \
     SphericalHarmonicTorqueSettings, \
     TorqueSettings, \
     aerodynamic_type, \
     dissipative_type, \
     inertial_type, \
     second_order_gravitational_type, \
     spherical_harmonic_gravitational_type, \
     torque_free_type, \
     underfined_type