# ====================================================================
#             WARNING: DO NOT MANUALLY CHANGE THIS FILE!
# ====================================================================
# 
# This file is automatically generated before every `tudatpy` release.
# The purpose of this file is manually import all members of 
# 
#     tudatpy.astro.two_body_dynamics
# 
# to make autocompletion suggestions of C++ tudatpy modules possible.

# ----------------------------------------
#                 METHODS                 
# ----------------------------------------
from tudatpy.kernel.astro.two_body_dynamics import \
     compute_escape_or_capture_delta_v, \
     propagate_kepler_orbit
# ----------------------------------------
#                 OBJECTS                 
# ----------------------------------------
from tudatpy.kernel.astro.two_body_dynamics import \
     EccentricityFindingFunctions, \
     LambertTargeter, \
     LambertTargeterGooding, \
     LambertTargeterIzzo, \
     MultiRevolutionLambertTargeterIzzo, \
     PericenterFindingFunctions, \
     ZeroRevolutionLambertTargeterIzzo