# ====================================================================
#             WARNING: DO NOT MANUALLY CHANGE THIS FILE!
# ====================================================================
# 
# This file is automatically generated before every `tudatpy` release.
# The purpose of this file is manually import all members of 
# 
#     tudatpy.numerical_simulation.propagation_setup.propagator
# 
# to make autocompletion suggestions of C++ tudatpy modules possible.

# ----------------------------------------
#                 METHODS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.propagation_setup.propagator import \
     add_dependent_variable_settings, \
     cpu_time_termination, \
     custom_state, \
     custom_termination, \
     custom_termination_with_state_input, \
     dependent_variable_termination, \
     hybrid_arc, \
     hybrid_termination, \
     mass, \
     multi_arc, \
     multitype, \
     non_sequential_termination, \
     rotational, \
     time_termination, \
     translational
# ----------------------------------------
#                 OBJECTS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.propagation_setup.propagator import \
     CustomStatePropagatorSettings, \
     HybridArcPropagatorProcessingSettings, \
     HybridArcPropagatorSettings, \
     MassPropagatorSettings, \
     MultiArcPropagatorProcessingSettings, \
     MultiArcPropagatorSettings, \
     MultiTypePropagatorSettings, \
     NonSequentialPropagationTerminationSettings, \
     PropagationCPUTimeTerminationSettings, \
     PropagationCustomTerminationSettings, \
     PropagationDependentVariableTerminationSettings, \
     PropagationHybridTerminationSettings, \
     PropagationPrintSettings, \
     PropagationTerminationSettings, \
     PropagationTerminationTypes, \
     PropagationTimeTerminationSettings, \
     PropagatorProcessingSettings, \
     PropagatorSettings, \
     RotationalPropagatorType, \
     RotationalStatePropagatorSettings, \
     SingleArcPropagatorProcessingSettings, \
     SingleArcPropagatorSettings, \
     StateType, \
     TranslationalPropagatorType, \
     TranslationalStatePropagatorSettings, \
     cowell, \
     cpu_time_stopping_condition_type, \
     custom_stopping_condition_type, \
     custom_type, \
     dependent_variable_stopping_condition_type, \
     encke, \
     exponential_map, \
     gauss_keplerian, \
     gauss_modified_equinoctial, \
     hybrid_stopping_condition_type, \
     hybrid_type, \
     mass_type, \
     modified_rodrigues_parameters, \
     quaternions, \
     rotational_type, \
     time_stopping_condition_type, \
     translational_type, \
     undefined_rotational_propagator, \
     undefined_translational_propagator, \
     unified_state_model_exponential_map, \
     unified_state_model_modified_rodrigues_parameters, \
     unified_state_model_quaternions