# ====================================================================
#             WARNING: DO NOT MANUALLY CHANGE THIS FILE!
# ====================================================================
# 
# This file is automatically generated before every `tudatpy` release.
# The purpose of this file is manually import all members of 
# 
#     tudatpy.numerical_simulation.estimation_setup.parameter
# 
# to make autocompletion suggestions of C++ tudatpy modules possible.

# ----------------------------------------
#                 METHODS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.estimation_setup.parameter import \
     absolute_observation_bias, \
     arcwise_absolute_observation_bias, \
     arcwise_constant_drag_coefficient, \
     arcwise_constant_empirical_acceleration_terms, \
     arcwise_empirical_accelerations, \
     arcwise_radiation_pressure_coefficient, \
     arcwise_relative_observation_bias, \
     arcwise_time_drift_observation_bias, \
     constant_drag_coefficient, \
     constant_empirical_acceleration_terms, \
     constant_rotation_rate, \
     core_factor, \
     custom_analytical_partial, \
     custom_numerical_partial, \
     custom_parameter, \
     direct_tidal_dissipation_time_lag, \
     empirical_accelerations, \
     free_core_nutation_rate, \
     gravitational_parameter, \
     ground_station_position, \
     initial_states, \
     inverse_tidal_quality_factor, \
     mean_moment_of_inertia, \
     order_invariant_k_love_number, \
     order_varying_k_love_number, \
     periodic_spin_variations, \
     polar_motion_amplitudes, \
     ppn_parameter_beta, \
     ppn_parameter_gamma, \
     quasi_impulsive_shots, \
     radiation_pressure_coefficient, \
     relative_observation_bias, \
     rotation_pole_position, \
     scaled_longitude_libration_amplitude, \
     spherical_harmonics_c_coefficients, \
     spherical_harmonics_c_coefficients_block, \
     spherical_harmonics_s_coefficients, \
     spherical_harmonics_s_coefficients_block, \
     time_drift_observation_bias, \
     yarkovsky_parameter
# ----------------------------------------
#                 OBJECTS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.estimation_setup.parameter import \
     CustomAccelerationPartialSettings, \
     EstimatableParameterSettings, \
     EstimatableParameterTypes, \
     arc_wise_constant_drag_coefficient_type, \
     arc_wise_empirical_acceleration_coefficients_type, \
     arc_wise_initial_body_state_type, \
     arc_wise_radiation_pressure_coefficient_type, \
     arc_wise_time_drift_observation_bias_type, \
     arcwise_constant_additive_observation_bias_type, \
     arcwise_constant_relative_observation_bias_type, \
     constant_additive_observation_bias_type, \
     constant_drag_coefficient_type, \
     constant_relative_observation_bias_type, \
     constant_rotation_rate_type, \
     constant_time_drift_observation_bias_type, \
     core_factor_type, \
     desaturation_delta_v_values_type, \
     direct_dissipation_tidal_time_lag_type, \
     empirical_acceleration_coefficients_type, \
     equivalence_principle_lpi_violation_parameter_type, \
     free_core_nutation_rate_type, \
     full_degree_tidal_love_number_type, \
     gravitational_parameter_type, \
     ground_station_position_type, \
     initial_body_state_type, \
     initial_rotational_body_state_type, \
     inverse_tidal_quality_factor_type, \
     mean_moment_of_inertia_type, \
     periodic_spin_variation_type, \
     polar_motion_amplitude_type, \
     ppn_parameter_beta_type, \
     ppn_parameter_gamma_type, \
     radiation_pressure_coefficient_type, \
     rotation_pole_position_type, \
     single_degree_variable_tidal_love_number_type, \
     spherical_harmonics_cosine_coefficient_block_type, \
     spherical_harmonics_sine_coefficient_block_type