# ====================================================================
#             WARNING: DO NOT MANUALLY CHANGE THIS FILE!
# ====================================================================
# 
# This file is automatically generated before every `tudatpy` release.
# The purpose of this file is manually import all members of 
# 
#     tudatpy.numerical_simulation.environment_setup.aerodynamic_coefficients
# 
# to make autocompletion suggestions of C++ tudatpy modules possible.

# ----------------------------------------
#                 METHODS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.environment_setup.aerodynamic_coefficients import \
     constant, \
     constant_force_and_moment, \
     custom_aerodynamic_force_and_moment_coefficients, \
     custom_aerodynamic_force_coefficients, \
     custom_control_surface, \
     scaled_by_constant, \
     scaled_by_vector, \
     scaled_by_vector_function, \
     tabulated, \
     tabulated_force_only, \
     tabulated_force_only_from_files, \
     tabulated_from_files, \
     tabulated_from_files_control_surface
# ----------------------------------------
#                 OBJECTS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.environment_setup.aerodynamic_coefficients import \
     AerodynamicCoefficientSettings, \
     ConstantAerodynamicCoefficientSettings, \
     ControlSurfaceIncrementAerodynamicCoefficientSettings, \
     CustomAerodynamicCoefficientSettings, \
     CustomControlSurfaceIncrementAerodynamicCoefficientSettings, \
     ScaledAerodynamicCoefficientInterfaceSettings