name: tudatpy-docs-readthedocs
channels:
  - conda-forge
  - tudat-team/label/test
  - tudat-team
dependencies:
  # All standard tudat-bundle deps are needed for sphinx-documentation for tudatpy.
  # Skipping listing tudat and boost-cpp here because they will be installed as part of tudatpy installation
  - basemap # for tudat.plotting
  - basemap-data-hires # for tudat.plotting
  # Other doc related
  - jinja2
  - yaml
  - pydantic=1.10.9
  - numpydoc
  - tudatpy
  - boost-cpp=1.84.0
  - pip
  - pip:
     - nbsphinx
     - sphinxcontrib-napoleon
     - sphinx_rtd_theme
     - sphinxcontrib-fulltoc
     - sphinxcontrib-bibtex
     - furo
     - sphinx_copybutton
