# ====================================================================
#             WARNING: DO NOT MANUALLY CHANGE THIS FILE!
# ====================================================================
# 
# This file is automatically generated before every `tudatpy` release.
# The purpose of this file is manually import all members of 
# 
#     tudatpy.numerical_simulation.environment_setup.shape
# 
# to make autocompletion suggestions of C++ tudatpy modules possible.

# ----------------------------------------
#                 METHODS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.environment_setup.shape import \
     hybrid, \
     oblate_spherical, \
     polyhedron, \
     spherical, \
     spherical_spice
# ----------------------------------------
#                 OBJECTS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.environment_setup.shape import \
     BodyShapeSettings, \
     HybridBodyShapeSettings, \
     OblateSphericalBodyShapeSettings, \
     PolyhedronBodyShapeSettings, \
     SphericalBodyShapeSettings