Import/Include Statements:

Environment Setup:
  - Create bodies
  - Create vehicle
  - [Conditional] Create interfaces
  - Finalize body creation

Propagation Setup:
  - [Conditional] Create thrust guidance settings
  - Create acceleration models
  - Create Initial System State
  - [Conditional] Create dependent variable save settings
  - [Conditional] Create termination settings
  - Create propagator settings
  - [Estimation Setup] Create estimated parameters
  - [Conditional, Estimation Setup] Define observable link ends
  - [Conditional, Estimation Setup] Create observation settings
  - Create integrator settings

Simulate:
  - Create dynamics simulator
  - Retrieve result
  - Visualize/Analyse/Save result

Simulate & Estimate:
  - Create OD manager object (propagates dynamics and variational equations)
  - Define observation simulation settings
  - Simulate observations
  - Define estimate settings
  - Perform estimation
  - Retrieve result
  - Visualize/Analyse/Save result
