# ====================================================================
#             WARNING: DO NOT MANUALLY CHANGE THIS FILE!
# ====================================================================
# 
# This file is automatically generated before every `tudatpy` release.
# The purpose of this file is manually import all members of 
# 
#     tudatpy.numerical_simulation.propagation_setup.thrust
# 
# to make autocompletion suggestions of C++ tudatpy modules possible.

# ----------------------------------------
#                 METHODS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.propagation_setup.thrust import \
     constant_thrust_magnitude, \
     custom_thrust_acceleration_magnitude, \
     custom_thrust_acceleration_magnitude_fixed_isp, \
     custom_thrust_direction, \
     custom_thrust_magnitude, \
     custom_thrust_magnitude_fixed_isp, \
     custom_thrust_orientation, \
     get_propulsion_input_variables, \
     thrust_direction_from_state_guidance, \
     thrust_from_existing_body_orientation
# ----------------------------------------
#                 OBJECTS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.propagation_setup.thrust import \
     ConstantThrustMagnitudeSettings, \
     CustomThrustDirectionSettings, \
     CustomThrustMagnitudeSettings, \
     CustomThrustOrientationSettings, \
     ThrustDirectionFromStateGuidanceSettings, \
     ThrustDirectionGuidanceTypes, \
     ThrustDirectionSettings, \
     ThrustFrames, \
     ThrustMagnitudeSettings, \
     ThrustMagnitudeTypes, \
     inertial_thrust_frame_type, \
     tnw_thrust_frame_type, \
     unspecified_thrust_frame_type