# ====================================================================
#             WARNING: DO NOT MANUALLY CHANGE THIS FILE!
# ====================================================================
# 
# This file is automatically generated before every `tudatpy` release.
# The purpose of this file is manually import all members of 
# 
#     tudatpy.numerical_simulation.environment
# 
# to make autocompletion suggestions of C++ tudatpy modules possible.

# ----------------------------------------
#                 METHODS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.environment import \
     get_default_local_inclination_angle_of_attack_points, \
     get_default_local_inclination_mach_points, \
     get_default_local_inclination_sideslip_angle_points, \
     get_local_inclination_mesh, \
     get_local_inclination_total_vehicle_area, \
     save_vehicle_mesh_to_file, \
     transform_to_inertial_orientation
# ----------------------------------------
#                 OBJECTS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.environment import \
     AerodynamicAngleCalculator, \
     AerodynamicAngleRotationalEphemeris, \
     AerodynamicCoefficientFrames, \
     AerodynamicCoefficientGenerator36, \
     AerodynamicCoefficientInterface, \
     AerodynamicCoefficientsIndependentVariables, \
     AerodynamicsReferenceFrameAngles, \
     AerodynamicsReferenceFrames, \
     AtmosphereModel, \
     AtmosphericCompositionSpecies, \
     AtmosphericFlightConditions, \
     Body, \
     BodyShapeModel, \
     ConstantEphemeris, \
     ConstantTransmittingFrequencyCalculator, \
     ControlSurfaceIncrementAerodynamicInterface, \
     CustomBodyFixedDirectionCalculator, \
     CustomControlSurfaceIncrementAerodynamicInterface, \
     CustomInertialDirectionBasedRotationalEphemeris, \
     DirectLongitudeLibrationCalculator, \
     EarthOrientationAnglesCalculator, \
     EngineModel, \
     Ephemeris, \
     FlightConditions, \
     GcrsToItrsRotationModel, \
     GravityFieldModel, \
     GravityFieldVariationModel, \
     GroundStation, \
     GroundStationState, \
     HypersonicLocalInclinationAnalysis, \
     InertialBodyFixedDirectionCalculator, \
     KeplerEphemeris, \
     LongitudeLibrationCalculator, \
     MultiArcEphemeris, \
     PointingAnglesCalculator, \
     PolyhedronGravityField, \
     RigidBodyProperties, \
     RotationalEphemeris, \
     SphericalHarmonicsGravityField, \
     SynchronousRotationalEphemeris, \
     SystemOfBodies, \
     TabulatedEphemeris, \
     TimeDependentSphericalHarmonicsGravityField, \
     TimingSystem, \
     Tle, \
     TleEphemeris, \
     TransmittingFrequencyCalculator, \
     VehicleSystems, \
     aerodynamic_frame, \
     altitude_dependent, \
     angle_of_attack, \
     angle_of_attack_dependent, \
     angle_of_sideslip, \
     anomalous_o_number_density_dependent, \
     anomalous_o_species, \
     ar_number_density_dependent, \
     ar_species, \
     bank_angle, \
     body_frame, \
     control_surface_deflection_dependent, \
     corotating_frame, \
     flight_path_angle, \
     h_number_density_dependent, \
     h_species, \
     he_number_density_dependent, \
     he_species, \
     heading_angle, \
     inertial_frame, \
     latitude_angle, \
     longitude_angle, \
     mach_number_dependent, \
     n2_number_density_dependent, \
     n2_species, \
     n_number_density_dependent, \
     n_species, \
     negative_aerodynamic_frame_coefficients, \
     negative_body_fixed_frame_coefficients, \
     o2_number_density_dependent, \
     o2_species, \
     o_number_density_dependent, \
     o_species, \
     positive_aerodynamic_frame_coefficients, \
     positive_body_fixed_frame_coefficients, \
     sideslip_angle_dependent, \
     temperature_dependent, \
     time_dependent, \
     trajectory_frame, \
     undefined_independent_variable, \
     velocity_dependent, \
     vertical_frame