# ====================================================================
#             WARNING: DO NOT MANUALLY CHANGE THIS FILE!
# ====================================================================
# 
# This file is automatically generated before every `tudatpy` release.
# The purpose of this file is manually import all members of 
# 
#     tudatpy.astro.gravitation
# 
# to make autocompletion suggestions of C++ tudatpy modules possible.

# ----------------------------------------
#                 METHODS                 
# ----------------------------------------
from tudatpy.kernel.astro.gravitation import \
     legendre_normalization_factor, \
     normalize_spherical_harmonic_coefficients, \
     spherical_harmonic_coefficients_from_inertia, \
     unnormalize_spherical_harmonic_coefficients