#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# tudat-api documentation build configuration file, created by
# sphinx-quickstart on Sat May  8 16:14:17 2021.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

import os
import sys
import importlib
import re
from datetime import datetime

from sphinx.util import logging as sphinx_logging

LOGGER = sphinx_logging.getLogger(__name__)

sys.path.insert(0, os.path.abspath("."))

# When the docs are being built on ReadTheDocs, the binaries are in the tudatpy conda package installed in site-packages directory.
if bool(os.getenv("READTHEDOCS")) is True:
    import importlib.util

    # Find the path where the package is installed
    tudatpy_path = importlib.util.find_spec("tudatpy").origin

    # Extract the directory up to site-packages
    site_packages_path = os.path.dirname(os.path.dirname(tudatpy_path))

    # Print the path
    print(f"site-packages path is: {site_packages_path}")

    # Insert the site-packages path to sys.path
    sys.path.insert(0, os.path.abspath(site_packages_path))
    print("sys.path:", sys.path)

else:
    # when building locally, use the binaries generated with tudat-bundle
    sys.path.insert(0, os.path.abspath("../../../build/tudatpy"))


def has_mcd_support():
    """Return whether the imported tudatpy build exposes atmosphere.mcd."""
    try:
        atmosphere = importlib.import_module("tudatpy.dynamics.environment_setup.atmosphere")
    except Exception:
        return False
    return hasattr(atmosphere, "mcd")


HAS_MCD_SUPPORT = has_mcd_support()


def filter_mcd_docs(app, docname, source):
    """Hide MCD docs when the imported tudatpy build has no MCD support."""
    if docname != "dynamics/environment_setup/atmosphere" or HAS_MCD_SUPPORT:
        return

    text = source[0]
    text = text.replace("\n   mcd\n", "\n")
    text = text.replace(
        "\n.. autofunction:: tudatpy.dynamics.environment_setup.atmosphere.mcd\n",
        "\n",
    )
    source[0] = text


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.intersphinx",
    "sphinx.ext.autosummary",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "sphinx.ext.mathjax",
    "sphinx.ext.ifconfig",
    "sphinx.ext.viewcode",
    "sphinx.ext.githubpages",
    "sphinx.ext.napoleon",
    # "sphinx.ext.autosectionlabel", # removed to avoid conflicts of class/function heading labels
    "sphinx_copybutton",
    # 'breathe',
    # 'exhale'
    "sphinxcontrib.bibtex",
]
autosummary_generate = True  # Turn on sphinx.ext.autosummary

add_module_names = False
autodoc_member_order = "groupwise"


autodoc_default_options = {
    "show-inheritance": True,
}

bibtex_bibfiles = ["refs.bib"]
bibtex_default_style = "plain"

# napoleon_type_aliases = {
#     "Dict": ":class:`~typing.Dict`",
#     "Callable": ":class:`~typing.Callable`",
#     "List": ":class:`~typing.List`",
# }

# custom section to define the size of dependent variables
napoleon_custom_sections = [("Variable Size", "params_style")]
# to not skip __init__
# def skip(app, what, name, obj, would_skip, options):
#     if name == "__init__":
#         return False
#     return would_skip
#
#
# def setup(app):
#     app.connect("autodoc-skip-member", skip)


def process_constants_docstring(app, what, name, obj, options, lines):
    """
    Function to remove the default docstring generated by autodoc for data objects and replace it with the type information.

    Assuming that the constants are documented using the .. autodata:: directive, this function will remove the default docstring generated by autodoc and replace it with the type information.
    The type information is directly inferred from the variable and thus does not need to be manually specified in the docstring.
    The docstring in the .rst file will be appended to this type information.
    The function applies only to the modules specified in the modules_to_process list.
    """

    modules_to_process = ("tudatpy.constants",)

    attribute_module = name.rsplit(".", 1)[0]

    if (what == "data") and (attribute_module in modules_to_process):

        lines.clear()
        # retrieve variable type directly from the object
        lines.append(f":type: {type(obj).__name__}")


NUMPY_DOCSTRING_SECTION_TITLES = {
    "Parameters",
    "Returns",
    "Yields",
    "Raises",
    "Warns",
    "Warnings",
    "Examples",
    "Notes",
    "See Also",
    "Attributes",
    "Methods",
    "References",
}


def _leading_whitespace_width(text: str) -> int:
    """Return indentation width of a line in spaces."""
    return len(text) - len(text.lstrip())


def _is_dash_underline(text: str) -> bool:
    """Return whether a line is a non-empty dash-only underline."""
    stripped = text.strip()
    return bool(stripped) and set(stripped) == {"-"}


def _is_numpy_section_header(lines, index: int) -> bool:
    """Check whether lines[index:index+2] form a NumPy-style section header.

    The section header consists of a title line (with text in NUMPY_DOCSTRING_SECTION_TITLES) followed by an underline line of dashes.
    The title and underline must have the same indentation, and the underline must be at least as
    long as the title.
    """

    if index + 1 >= len(lines):
        return False

    title_line = lines[index]
    underline_line = lines[index + 1]
    title = title_line.strip()

    if title not in NUMPY_DOCSTRING_SECTION_TITLES:
        return False

    if not _is_dash_underline(underline_line):
        return False

    if _leading_whitespace_width(title_line) != _leading_whitespace_width(underline_line):
        return False

    if len(underline_line.strip()) < len(title):
        return False

    return True


def _is_overloaded_pybind_docstring(lines) -> bool:
    """Detect pybind-generated overloaded-function docstrings."""
    return any(line.strip() == "Overloaded function." for line in lines[:3])


def _rewrite_overloaded_list_items(lines):
    """Rewrite numbered overload entries into labeled code-style signatures.

    This function detects lines of the form "   1. signature" in pybind-generated docstrings for overloaded functions and rewrites them into a more Sphinx-friendly format:
         Overload 1:
         ``signature``
    This allows Sphinx to correctly parse the signatures and display them in the documentation, rather than treating them as plain text list items.
    """

    OVERLOAD_LIST_ITEM_PATTERN = re.compile(r"^(\s*)(\d+)\.\s+(.*)$")

    rewritten_lines = []
    for line in lines:
        match = OVERLOAD_LIST_ITEM_PATTERN.match(line)
        if match is None:
            rewritten_lines.append(line)
            continue

        indent, index, signature = match.groups()
        rewritten_lines.append(f"{indent}Overload {index}:")
        rewritten_lines.append(f"{indent}``{signature}``")

    return rewritten_lines


def _dedent_to_numpy_headers(lines):
    """Dedent all docstring lines to the minimum NumPy-section header indent.

    This function detects all NumPy-style section headers in the docstring and computes the minimum indentation among them. It then dedents all lines by that amount, ensuring that section headers are flush with the left margin and that relative indentation within sections is preserved.
    """

    header_indents = []

    for i in range(len(lines) - 1):
        title = lines[i].strip()
        underline = lines[i + 1]

        if (
            title in NUMPY_DOCSTRING_SECTION_TITLES
            and _is_dash_underline(underline)
            and len(underline.strip()) >= len(title)
        ):
            header_indents.append(_leading_whitespace_width(lines[i]))

    if not header_indents:
        return lines

    base_indent = min(header_indents)

    return [
        line[base_indent:] if _leading_whitespace_width(line) >= base_indent else line
        for line in lines
    ]


def fix_docstring_section_title_spacing(app, what, name, obj, options, lines):
    """Fix docstring section title spacing for Sphinx parsing.

    This function processes docstrings to ensure that NumPy-style section headers are correctly recognized by Sphinx. It detects section headers, ensures they are flush with the left margin, and that they are followed by an empty line if needed. This allows Sphinx to properly parse the sections and display them in the documentation.
    This fixes `CRITICAL: Unexpected section title.` errors in the Sphinx build.
    """

    if not lines:
        return

    try:
        working_lines = list(lines)

        if _is_overloaded_pybind_docstring(working_lines):
            working_lines = _rewrite_overloaded_list_items(working_lines)

        working_lines = _dedent_to_numpy_headers(working_lines)

        normalized_lines = []
        i = 0

        while i < len(working_lines):
            if _is_numpy_section_header(working_lines, i):
                normalized_lines.append(working_lines[i])
                normalized_lines.append(working_lines[i + 1])

                has_content_line = (i + 2) < len(working_lines)
                missing_empty_line = has_content_line and working_lines[i + 2].strip() != ""
                if missing_empty_line:
                    empty_line = " " * _leading_whitespace_width(working_lines[i])
                    normalized_lines.append(empty_line)

                i += 2
                continue

            normalized_lines.append(working_lines[i])
            i += 1

        lines[:] = normalized_lines

    except Exception as exc:

        LOGGER.warning(
            f"Docstring preprocessing failed for {{{name}}} ({what}): {exc}. Leaving original docstring unchanged.",
            exc_info=True,
        )
        return


def replace_annotated_nparrays(text: str) -> str:
    """
    Replace typing.Annotated[numpy.typing.ArrayLike, <dtype>, "[<shape>]"]
    with numpy.ndarray[<dtype>[<shape>]] inside a larger string.
    """

    pattern_arraylike = re.compile(
        r"""
        typing\.Annotated\[
            \s*numpy\.typing\.ArrayLike\s*,
            \s*(?P<dtype>[^,\]]+)\s*,
            \s*"\[(?P<shape>[^\]]+)\]"\s*
        \]
        """,
        re.VERBOSE,
    )

    pattern_ndarray = re.compile(
        r"""
        typing\.Annotated\[
            \s*numpy\.typing\.NDArray
            \[
                \s*(?P<dtype>[^\]]+)\s*
            \]
            \s*,\s*
            "\[(?P<shape>[^\]]+)\]"
            \s*
        \]
        """,
        re.VERBOSE,
    )

    def repl(match: re.Match) -> str:
        dtype = match.group("dtype").strip()
        shape = match.group("shape").strip()
        return f"numpy.ndarray[{dtype}[{shape}]]"

    text = pattern_arraylike.sub(repl, text)
    text = pattern_ndarray.sub(repl, text)

    return text


def simplify_signature_types(app, what, name, obj, options, signature, return_annotation):

    # map complex type hints to simpler representations
    type_replacements = {
        "typing.SupportsInt": "int",
        "typing.SupportsFloat": "float",
        "typing.List": "list",
        "typing.Dict": "dict",
        "typing.Callable": "Callable",
        "typing.Any": "any",
        "collections.abc.Sequence": "list",
        "collections.abc.Mapping": "dict",
        "collections.abc.Callable": "Callable",
        "SupportsFloat": "float",
        "SupportsInt": "int",
    }

    for full_type, simple_type in type_replacements.items():
        if signature:
            signature = signature.replace(full_type, simple_type)
        if return_annotation:
            return_annotation = return_annotation.replace(full_type, simple_type)

    if signature:
        signature = replace_annotated_nparrays(signature)
    if return_annotation:
        return_annotation = replace_annotated_nparrays(return_annotation)

    return signature, return_annotation


def setup(app):
    app.connect("autodoc-process-docstring", process_constants_docstring)
    # run before default-priority (500) docstring processors
    app.connect("autodoc-process-docstring", fix_docstring_section_title_spacing, priority=200)
    app.connect("autodoc-process-signature", simplify_signature_types)
    app.connect("source-read", filter_mcd_docs)


# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "TudatPy API"
year = datetime.now().year
copyright = f"{year}, Tudat Team"
author = "Tudat Team"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = ""
# The full version, including alpha/beta/rc tags.
release = ""

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'sphinx_rtd_theme'
html_theme = "furo"
html_theme_options = {
    "navigation_with_keys": True,
    "announcement": "TudatPy v1.0 has been released 🥳 See the <a href='https://docs.tudat.space/en/latest/user-guide/project-updates/migration-guide.html'>migration guide</a> or contact us in our <a href='https://github.com/orgs/tudat-team/discussions?discussions_q='>Github Discussion forum</a> for any questions!",
    # "announcement": "Have questions or feedback? See the <a href='https://docs.tudat.space/en/latest/index_user_guide.html'>User Guide</a> or let us know in our <a href='https://github.com/orgs/tudat-team/discussions?discussions_q='>Github Discussion forum</a>!",
}

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_css_files = [
    "style.css",
]
# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
# html_sidebars = {
#     '**': [
#         'relations.html',  # needs 'show_related': True theme option to display
#         'searchbox.html',
#     ]
# }

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "TudatPy API"
html_title = "TudatPy API Reference"

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, "tudat-api.tex", "TudatPy API", "John", "manual"),
]

# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "tudat-api", "TudatPy API", [author], 1)]

# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "tudat-api",
        "TudatPy API",
        author,
        "tudat-api",
        "One line description of project.",
        "Miscellaneous",
    ),
]

# Example configuration for intersphinx: refer to the Python standard library.

# intersphinx_mapping = {'https://docs.python.org/': None}

intersphinx_mapping = {
    "python": ("https://docs.python.org/", None),
    "sphinx": ("https://www.sphinx-doc.org/en/master/", None),
    "pagmo": ("https://esa.github.io/pagmo2/", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
    "matplotlib": ("https://matplotlib.org/stable/", None),
    "pandas": ("https://pandas.pydata.org/pandas-docs/stable/", None),
}
