# ====================================================================
#             WARNING: DO NOT MANUALLY CHANGE THIS FILE!
# ====================================================================
# 
# This file is automatically generated before every `tudatpy` release.
# The purpose of this file is manually import all members of 
# 
#     tudatpy.numerical_simulation.propagation_setup.acceleration
# 
# to make autocompletion suggestions of C++ tudatpy modules possible.

# ----------------------------------------
#                 METHODS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.propagation_setup.acceleration import \
     aerodynamic, \
     cannonball_radiation_pressure, \
     custom, \
     custom_acceleration, \
     direct_tidal_dissipation_acceleration, \
     empirical, \
     mutual_spherical_harmonic_gravity, \
     point_mass_gravity, \
     polyhedron_gravity, \
     quasi_impulsive_shots_acceleration, \
     radiation_pressure, \
     relativistic_correction, \
     ring_gravity, \
     spherical_harmonic_gravity, \
     thrust_and_isp_from_custom_function, \
     thrust_from_all_engines, \
     thrust_from_custom_function, \
     thrust_from_direction_and_magnitude, \
     thrust_from_engine, \
     thrust_from_engines, \
     yarkovsky
# ----------------------------------------
#                 OBJECTS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.propagation_setup.acceleration import \
     AccelerationSettings, \
     AvailableAcceleration, \
     CustomAccelerationSettings, \
     DirectTidalDissipationAccelerationSettings, \
     EmpiricalAccelerationSettings, \
     MomentumWheelDesaturationAccelerationSettings, \
     MutualSphericalHarmonicAccelerationSettings, \
     RelativisticAccelerationCorrectionSettings, \
     SphericalHarmonicAccelerationSettings, \
     ThrustAccelerationSettings, \
     aerodynamic_type, \
     cannonball_radiation_pressure_type, \
     custom_acceleration_type, \
     direct_tidal_dissipation_in_central_body_acceleration_type, \
     direct_tidal_dissipation_in_orbiting_body_acceleration_type, \
     empirical_acceleration_type, \
     mutual_spherical_harmonic_gravity_type, \
     point_mass_gravity_type, \
     polyhedron_gravity_type, \
     quasi_impulsive_shots_acceleration_type, \
     radiation_pressure_type, \
     relativistic_correction_acceleration_type, \
     spherical_harmonic_gravity_type, \
     thrust_acceleration_type, \
     undefined_acceleration_type