# ====================================================================
#             WARNING: DO NOT MANUALLY CHANGE THIS FILE!
# ====================================================================
# 
# This file is automatically generated before every `tudatpy` release.
# The purpose of this file is manually import all members of 
# 
#     tudatpy.data
# 
# to make autocompletion suggestions of C++ tudatpy modules possible.

# ----------------------------------------
#                 METHODS                 
# ----------------------------------------
from tudatpy.kernel.data import \
     get_atmosphere_tables_path, \
     get_earth_orientation_path, \
     get_ephemeris_path, \
     get_gravity_models_path, \
     get_quadrature_path, \
     get_resource_path, \
     get_space_weather_path, \
     get_spice_kernel_path, \
     grail_antenna_file_reader, \
     grail_mass_level_0_file_reader, \
     grail_mass_level_1_file_reader, \
     read_matrix_history_from_file, \
     read_odf_file, \
     read_solar_activity_data, \
     read_tracking_txt_file, \
     read_vector_history_from_file, \
     set_dsn_weather_data_in_ground_stations
# ----------------------------------------
#                 OBJECTS                 
# ----------------------------------------
from tudatpy.kernel.data import \
     DynamicCoefficientNames, \
     OdfRawFileContents, \
     SolarActivityData, \
     StaticCoefficientNames, \
     TrackingDataType, \
     TrackingTxtFileContents, \
     ca, \
     cap, \
     caq, \
     car, \
     clb, \
     cll, \
     cllp, \
     cllq, \
     cllr, \
     cln, \
     clnp, \
     clnq, \
     clnr, \
     cm, \
     cma, \
     cmad, \
     cmp, \
     cmq, \
     cmr, \
     cn, \
     cna, \
     cnad, \
     cnb, \
     cnp, \
     cnq, \
     cnr, \
     cy, \
     cyb, \
     cyp, \
     cyq, \
     cyr, \
     day, \
     doppler_bandwidth, \
     doppler_base_frequency, \
     doppler_measured_frequency, \
     doppler_noise, \
     downlink_frequency, \
     dsn_receiving_station_nr, \
     dsn_transmitting_station_nr, \
     file_name, \
     hour, \
     light_time_measurement_accuracy, \
     light_time_measurement_delay, \
     minute, \
     missile_DATCOM_data, \
     month, \
     n_way_light_time, \
     observation_body, \
     observation_time_scale, \
     observed_body, \
     planet_nr, \
     receiving_station_name, \
     residual_de405, \
     second, \
     signal_to_noise, \
     spacecraft_id, \
     spacecraft_transponder_delay, \
     spectral_max, \
     tdb_spacecraft_j2000, \
     time_tag_delay, \
     transmitting_station_name, \
     uplink_frequency, \
     vx_planet_frame, \
     vy_planet_frame, \
     vz_planet_frame, \
     x_planet_frame, \
     y_planet_frame, \
     year, \
     z_planet_frame