# ====================================================================
#             WARNING: DO NOT MANUALLY CHANGE THIS FILE!
# ====================================================================
# 
# This file is automatically generated before every `tudatpy` release.
# The purpose of this file is manually import all members of 
# 
#     tudatpy.numerical_simulation.environment_setup
# 
# to make autocompletion suggestions of C++ tudatpy modules possible.

# ----------------------------------------
#                 METHODS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.environment_setup import \
     add_aerodynamic_coefficient_interface, \
     add_empty_tabulated_ephemeris, \
     add_engine_model, \
     add_flight_conditions, \
     add_ground_station, \
     add_mass_properties_model, \
     add_radiation_pressure_interface, \
     add_radiation_pressure_target_model, \
     add_rotation_model, \
     add_variable_direction_engine_model, \
     create_aerodynamic_coefficient_interface, \
     create_body_ephemeris, \
     create_ground_station_ephemeris, \
     create_radiation_pressure_interface, \
     create_simplified_system_of_bodies, \
     create_system_of_bodies, \
     create_tabulated_ephemeris_from_spice, \
     get_default_body_settings, \
     get_default_body_settings_time_limited, \
     get_default_single_alternate_body_settings, \
     get_default_single_alternate_body_settings_time_limited, \
     get_default_single_body_settings, \
     get_default_single_body_settings_time_limited, \
     get_ground_station_list, \
     get_safe_interpolation_interval, \
     get_target_elevation_angles, \
     set_aerodynamic_guidance, \
     set_aerodynamic_orientation_functions, \
     set_constant_aerodynamic_orientation
# ----------------------------------------
#                 OBJECTS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.environment_setup import \
     BodyListSettings, \
     BodySettings