# ====================================================================
#             WARNING: DO NOT MANUALLY CHANGE THIS FILE!
# ====================================================================
# 
# This file is automatically generated before every `tudatpy` release.
# The purpose of this file is manually import all members of 
# 
#     tudatpy.numerical_simulation.estimation
# 
# to make autocompletion suggestions of C++ tudatpy modules possible.

# ----------------------------------------
#                 METHODS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.estimation import \
     compute_residuals_and_dependent_variables, \
     compute_target_angles_and_range, \
     compute_target_angles_and_range_vectors, \
     create_best_fit_to_ephemeris, \
     create_filtered_observation_collection, \
     create_new_observation_collection, \
     create_pseudo_observations_and_models, \
     create_single_observation_set, \
     estimation_convergence_checker, \
     filter_observations, \
     observation_filter, \
     observation_parser, \
     observation_set_splitter, \
     propagate_covariance, \
     propagate_covariance_rsw_split_output, \
     propagate_covariance_split_output, \
     propagate_formal_errors, \
     propagate_formal_errors_rsw_split_output, \
     propagate_formal_errors_split_output, \
     set_existing_observations, \
     simulate_observations, \
     single_observation_set, \
     split_observation_collection, \
     split_observation_set
# ----------------------------------------
#                 OBJECTS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.estimation import \
     CombinedStateTransitionAndSensitivityMatrixInterface, \
     CovarianceAnalysisInput, \
     CovarianceAnalysisOutput, \
     EstimatableParameterSet, \
     EstimationConvergenceChecker, \
     EstimationInput, \
     EstimationOutput, \
     ObservationCollection, \
     ObservationCollectionParser, \
     ObservationFilterBase, \
     ObservationFilterType, \
     ObservationParserType, \
     ObservationSetSplitterBase, \
     ObservationSetSplitterType, \
     ObservationSimulator, \
     ObservationSimulator_1, \
     ObservationSimulator_2, \
     ObservationSimulator_3, \
     ObservationSimulator_6, \
     ObservationViabilityCalculator, \
     PodInput, \
     PodOutput, \
     SingleObservationSet, \
     absolute_value_filtering, \
     ancillary_settings_parser, \
     dependent_variable_filtering, \
     empty_parser, \
     epochs_filtering, \
     link_end_id_parser, \
     link_end_str_parser, \
     link_end_type_parser, \
     link_ends_parser, \
     multi_type_parser, \
     nb_observations_splitter, \
     observable_type_parser, \
     residual_filtering, \
     single_link_end_parser, \
     time_bounds_filtering, \
     time_bounds_parser, \
     time_interval_splitter, \
     time_span_splitter, \
     time_tags_splitter