# ====================================================================
#             WARNING: DO NOT MANUALLY CHANGE THIS FILE!
# ====================================================================
# 
# This file is automatically generated before every `tudatpy` release.
# The purpose of this file is manually import all members of 
# 
#     tudatpy.numerical_simulation.estimation
# 
# to make autocompletion suggestions of C++ tudatpy modules possible.

# ----------------------------------------
#                 METHODS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.estimation import \
     compute_target_angles_and_range, \
     compute_target_angles_and_range_vectors, \
     estimation_convergence_checker, \
     propagate_covariance, \
     propagate_covariance_rsw_split_output, \
     propagate_covariance_split_output, \
     propagate_formal_errors, \
     propagate_formal_errors_rsw_split_output, \
     propagate_formal_errors_split_output, \
     set_existing_observations, \
     simulate_observations, \
     single_observation_set
# ----------------------------------------
#                 OBJECTS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.estimation import \
     CombinedStateTransitionAndSensitivityMatrixInterface, \
     CovarianceAnalysisInput, \
     CovarianceAnalysisOutput, \
     EstimatableParameterSet, \
     EstimationConvergenceChecker, \
     EstimationInput, \
     EstimationOutput, \
     ObservationCollection, \
     ObservationSimulator, \
     ObservationSimulator_1, \
     ObservationSimulator_2, \
     ObservationSimulator_3, \
     ObservationSimulator_6, \
     ObservationViabilityCalculator, \
     PodInput, \
     PodOutput, \
     SingleObservationSet