# ====================================================================
#             WARNING: DO NOT MANUALLY CHANGE THIS FILE!
# ====================================================================
# 
# This file is automatically generated before every `tudatpy` release.
# The purpose of this file is manually import all members of 
# 
#     tudatpy.astro.polyhedron_utilities
# 
# to make autocompletion suggestions of C++ tudatpy modules possible.

# ----------------------------------------
#                 METHODS                 
# ----------------------------------------
from tudatpy.kernel.astro.polyhedron_utilities import \
     centroid, \
     inertia_tensor_from_density, \
     inertia_tensor_from_gravitational_parameter, \
     modify_centroid, \
     surface_area, \
     volume