# ====================================================================
#             WARNING: DO NOT MANUALLY CHANGE THIS FILE!
# ====================================================================
# 
# This file is automatically generated before every `tudatpy` release.
# The purpose of this file is manually import all members of 
# 
#     tudatpy.numerical_simulation.environment_setup.shape_deformation
# 
# to make autocompletion suggestions of C++ tudatpy modules possible.

# ----------------------------------------
#                 METHODS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.environment_setup.shape_deformation import \
     basic_solid_body_tidal, \
     degree_two_basic_solid_body_tidal, \
     iers_2010_solid_body_tidal, \
     ocean_tidal, \
     pole_tidal
# ----------------------------------------
#                 OBJECTS                 
# ----------------------------------------
from tudatpy.kernel.numerical_simulation.environment_setup.shape_deformation import \
     BasicSolidBodyDeformationSettings, \
     BodyDeformationSettings